### ISSUE TITLE
main.lisp missing export 

### ISSUE THREAD

**Issue by ggerules** [burtonsamograd/sxc#7]
Nice example!  
Very concise.

In main.lisp
Was 
(defpackage :main
   (:use cl))

Should be... 
(defpackage :main
   (:use cl)
   (:export main))

Now the script/makefile will build a executable.  
My environment, Ubuntu 16.04 sbcl version 1.4.5

**Comment by burtonsamograd** [comment]
Thank you.  I appreciate it. 

I'll patch this in shortly.

**Comment by burtonsamograd** [comment]
Should be good, thanks for the patch.
